<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="D:\workspace\utility packages\IOOperation\IOOperationUtilityServices\ThreadLockUtilityServices.PollySemaphoreSlimService.xUnit.Tests\README.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThreadLevelLockingUtilityServices\ThreadLevelLockingUtilityServices.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>